name: 'Continuous Integration'
on:
  push:
    branches-ignore:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  unit-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        node-version: [12.x, 14.x, 16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Install node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2-beta
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run unit tests
      run: |
        npm install -g npm
        npm install
        npm run test
  integration-tests:
    needs: unit-tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        node-version: [12.x, 14.x, 16.x]
        es-version: [7.6.1]
        jdk-version: [oraclejdk11]
    steps:
    - uses: actions/checkout@v2
    - name: Install node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2-beta
      with:
        node-version: ${{ matrix.node-version }}
    - name: Start elasticsearch ${{ matrix.es-version }} (${{ matrix.jdk-version }})
      env:
        ES_VERSION: ${{ matrix.es-version }}
        JDK_VERSION: ${{ matrix.jdk-version }}
      run: ./scripts/setup_ci.sh
    - name: Run integration tests
      run: |
        npm install -g npm
        npm install
        curl http://127.0.0.1:9200/
        ./bin/create_index
        npm run integration
  npm-publish:
    needs: [unit-tests, integration-tests]
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v2-beta
      with:
        node-version: 16.x
    - name: Run semantic-release
      env:
        GH_TOKEN: ${{ secrets.GH_SEMANTIC_RELEASE_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        curl "https://raw.githubusercontent.com/pelias/ci-tools/master/semantic-release.sh" | bash -
  build-docker-images:
    # run this job if the unit tests passed and the npm-publish job was a success or was skipped
    # note: github actions won't run a job if you don't call one of the status check functions, so `always()` is called since it evalutes to `true`
    if: ${{ always() && needs.unit-tests.result == 'success' && (needs.npm-publish.result == 'success' || needs.npm-publish.result == 'skipped') }}
    needs: [unit-tests, integration-tests, npm-publish]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: Build Docker images
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          curl "https://raw.githubusercontent.com/pelias/ci-tools/buildx/build-docker-images.sh" | bash -
